interval = 300
log_level = "info"
env = []
# features = ["PACKAGE_VERSIONS"]

[upstream]
url = "https://bldr.habitat.sh"

[target]
url = ""
authToken = ""

[[origin]]
name = "core"
channels = ["stable"]

# [[package]]
# name = "core/hab"
# contraint = "< 0.80.0"

# [[package]]
# name = "core/hab-pkg-export-docker"
# contraint = "< 0.80.0"
