{{#if cfg.interval ~}}
interval = {{cfg.interval}}
{{/if ~}}

{{#if cfg.log_level ~}}
log_level = "{{cfg.log_level}}"
{{/if ~}}

{{#if cfg.env ~}}
env = {{toToml cfg.env}}
{{/if ~}}

temp_dir = "{{pkg.svc_data_path}}"

{{#if cfg.features ~}}
features = {{toToml cfg.features}}
{{/if ~}}

{{#if cfg.upstream ~}}
[upstream]
{{toToml cfg.upstream}}
{{/if ~}}

{{#if cfg.target ~}}
[target]
{{toToml cfg.target}}
{{/if ~}}

{{#each cfg.origin as |o| ~}}
[[origin]]
name = "{{o.name}}"
channels = {{toToml o.channels}}
{{/each ~}}

{{#each cfg.package as |p| ~}}
[[package]]
name = "{{p.name}}"
constraint = {{toToml p.constraint}}
{{/each ~}}
