interval = {{cfg.interval}}
log_level = "{{cfg.log_level}}"
env = {{toToml cfg.env}}
temp_dir = "{{pkg.svc_data_path}}"
features = {{toToml cfg.features}}

[upstream]
{{toToml cfg.upstream}}

[target]
{{toToml cfg.target}}

{{#each cfg.origin as |o| ~}}
[[origin]]
name = "{{o.name}}"
channels = {{toToml o.channels}}
{{/each ~}}

{{#each cfg.package as |p| ~}}
[[package]]
name = "{{p.name}}"
constraint = {{toToml p.constraint}}
{{/each ~}}
